version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: notification-db
    restart: always
    environment:
      POSTGRES_DB: notification
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123@adm
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
